# Generated by Django 4.0.3 on 2022-04-23 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='eklenme_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
