# Generated by Django 4.0.3 on 2022-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0002_question_eklenme_tarihi_question_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Soru', 'verbose_name_plural': 'Sorular'},
        ),
        migrations.AddField(
            model_name='question',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
