# Generated by Django 4.0.3 on 2022-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0007_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Fen Bilimleri', max_length=75)),
                ('section', models.CharField(default='Unit-1', max_length=75)),
            ],
        ),
    ]
