# Generated by Django 4.0.3 on 2022-04-23 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0008_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='questionApp.categories'),
        ),
    ]
