# Generated by Django 4.0.3 on 2022-04-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default=('Fen Bilimleri', 'Unit-1'), on_delete=django.db.models.deletion.CASCADE, to='questionApp.category'),
        ),
    ]
