# Generated by Django 4.0.3 on 2022-04-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0009_remove_categories_question_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
