# Generated by Django 4.0.3 on 2022-04-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0011_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(default='Unit-one', max_length=75),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionApp.category'),
        ),
    ]
