# Generated by Django 4.0.3 on 2022-04-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0012_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
