# Generated by Django 4.0.3 on 2022-04-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0012_alter_category_section_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
