# Generated by Django 4.0.3 on 2022-04-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0013_remove_question_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
