# Generated by Django 4.0.3 on 2022-04-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0013_categories_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='information',
            field=models.TextField(default='Fen Bilimleri dersi standart sorular', max_length=250, null=True),
        ),
    ]
