# Generated by Django 4.0.3 on 2022-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0014_categories_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
