# Generated by Django 4.0.3 on 2022-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0015_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('information', models.TextField(default='Fen Bilimleri dersi standart sorular', max_length=250, null=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testler',
            },
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='information',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(related_name='questions', to='questionApp.test'),
        ),
    ]
