# Generated by Django 4.0.3 on 2022-04-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0017_alter_categories_slug_alter_test_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.ManyToManyField(related_name='tests', to='questionApp.question'),
        ),
    ]
