# Generated by Django 4.0.3 on 2022-04-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0018_test_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
