# Generated by Django 4.0.3 on 2022-04-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0019_rename_test_test_questions_remove_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
