# Generated by Django 4.0.3 on 2022-04-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0020_test_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default=1, upload_to='Test'),
            preserve_default=False,
        ),
    ]
