# Generated by Django 4.0.3 on 2022-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0023_question_test_alter_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.AlterField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(to='questionApp.question'),
        ),
    ]
