# Generated by Django 4.0.3 on 2022-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionApp', '0025_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.PositiveIntegerField(default=5, null=2),
        ),
    ]
